### ISSUE TITLE
Adapter starts, but data is not pulled

### ISSUE THREAD

**Issue by epcos71** [TA2k/ioBroker.smart-eq#2]
**Describe the bug**  
Adapter is started, but data is not refreshed. Request fails with error code 400. see log:

> smart-eq.0 | 2022-01-26 06:42:08.848 | error | {"error":"internal_error","error_description":"Unknown error occurred"}
> smart-eq.0 | 2022-01-26 06:42:08.847 | error | Error: Request failed with status code 400
> smart-eq.0 | 2022-01-26 06:42:08.847 | error | https://oneapp.microservice.smart.com/seqc/v0/vehicles/xxx/refresh-data
> smart-eq.0 | 2022-01-26 06:42:05.893 | error | {"error":"internal_error","error_description":"Unknown error occurred"}
> smart-eq.0 | 2022-01-26 06:42:05.893 | error | Error: Request failed with status code 400
> smart-eq.0 | 2022-01-26 06:42:03.424 | info | starting. Version 0.0.2 in C:/iobroker/node_modules/iobroker.smart-eq, node: v14.18.2, js-controller: 3.3.22

**To Reproduce**  
just start the adapter and have a look in the object datapoints and the log.

**Expected behavior**  
Adapter should start and data should be pulled via API.

**Screenshots & Logfiles**  
see above

**Versions:**  
 - Adapter version: 0.0.2
 - JS-Controller version: 5.2.13
 - Node version: 14.18.2
 - Operating system: Windows10 Pro 21H2

**Comment by TA2k** [comment]
Is the error new and is the app working?

**Comment by epcos71** [comment]
> Is the error new and is the app working?

ok, sorry. Error is there since yesterday, but I checked the app right now. There seems to be an internal server right now, I can not access. Sorry for that, I should have checked the app before...
